# Generated by Django 5.2 on 2026-06-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='活跃时段'),
        ),
    ]
