# Generated by Django 5.2 on 2026-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='内容'),
        ),
    ]
